name: Cleaner

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Cleanup
        run: node .github/workflows/cleaner.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Config
        run: |
          git config --global user.name 'Hexo'
          git config --global user.email 'hexo@users.noreply.github.com'
      - name: Commit
        run: |
          git checkout -b cleanup
          git add .
          git commit -m 'chore: clean up themes & plugins'
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin cleanup -f
      - name: Open PR
        run: |
          gh pr create -B master -H cleanup --title 'chore: clean up themes & plugins' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
